// I should turn this into a map
module.exports = [
  //Chest
 {id: 1, name: 'Flat Bench press', type: 'Compound', targets: 'csa'},
 {id: 2, name: 'Incline bench press', type: 'Compound', targets: 'csa'},
 {id: 3, name: 'DB Flat Press', type: 'Compound', targets: 'cs'},
 {id: 4, name: 'DB Incline Press', type: 'Compound', targets: 'cs'},
 {id: 5, name: 'Machine Flat Press', type: 'Isolation', targets: 'c'},
 {id: 6, name: 'Machine Incline Press', type: 'Isolation', targets: 'cs'},
 {id: 7, name: 'Machine Decline Press', type: 'Isolation', targets: 'c'},
 {id: 8, name: 'Chest Fly', type: 'Isolation', targets: 'c'},
  //Shoulders
 {id: 9, name: 'Overhead Press', type: 'Compound', targets: 'sa'},
 {id: 10, name: 'DB Overhead Press', type: 'Compound', targets: 's'},
 {id: 11, name: 'Machine Shoulder Press', type: 'Isolation', targets: 's'},
 {id: 12, name: 'Lateral Raise', type: 'Isolation', targets: 's'},
 {id: 13, name: 'Front Raise', type: 'Isolation', targets: 's'},
 {id: 14, name: 'Rear Delt Fly', type: 'Isolation', targets: 's'},
 {id: 15, name: 'Facepull', type: 'Compound', targets: 'sb'},
 {id: 16, name: 'Shrugs', type: 'Isolation', targets: 'sb'},
   //Back
 {id: 17, name: 'Pullup/Chinup', type: 'Compound', targets: 'bsa'},
 {id: 18, name: 'Barbell Row', type: 'Compound', targets: 'bsa'},
 {id: 19, name: 'DB Row', type: 'Compound', targets: 'bsa'},
 {id: 20, name: 'Cable Row', type: 'Compound', targets: 'bsa'},
 {id: 21, name: 'Machine Low Row', type: 'Isolation', targets: 'b'},
 {id: 22, name: 'Machine High Row', type: 'Isolation', targets: 'b'},
 {id: 23, name: 'Lat Pulldown', type: 'Compound', targets: 'bsa'},
 {id: 24, name: 'Lat Pullover', type: 'Isolation', targets: 'b'},
 {id: 25, name: 'Deadlift', type: 'Compound', targets: 'bl'},
 {id: 26, name: 'Back Extensions', type: 'Isolation', targets: 'bl'},
  //Legs
 {id: 27, name: 'Squat', type: 'Compound', targets: 'lb'},
 {id: 28, name: 'Front Squat', type: 'Compound', targets: 'lb'},
 {id: 29, name: 'Lunge', type: 'Compound', targets: 'l'},
 {id: 30, name: 'Leg Press', type: 'Compound', targets: 'l'},
 {id: 31, name: 'Machine Squat', type: 'Compound', targets: 'l'},
 {id: 32, name: 'Hack Squat', type: 'Isolation', targets: 'l'},
 {id: 33, name: 'Leg Extension', type: 'Isolation', targets: 'l'},
 {id: 34, name: 'Leg Curl', type: 'Isolation', targets: 'l'},
 {id: 35, name: 'Stiff Leg Deadlift', type: 'Compound', targets: 'lb'},
 {id: 36, name: 'Calf Raise', type: 'Isolation', targets: 'l'},
  //Arms
 {id: 37, name: 'DB Curl', type: 'Isolation', targets: 'a'},
 {id: 38, name: 'BB Curl', type: 'Isolation', targets: 'a'},
 {id: 39, name: 'Cable Curl', type: 'Isolation', targets: 'a'},
 {id: 40, name: 'Hammer Curl', type: 'Isolation', targets: 'a'},
 {id: 41, name: 'EZ Curl', type: 'Isolation', targets: 'a'},
 {id: 42, name: 'Reverse Curl', type: 'Isolation', targets: 'a'},
 {id: 43, name: 'Preacher Curl', type: 'Isolation', targets: 'a'},
 {id: 44, name: 'Skullcrusher', type: 'Isolation', targets: 'a'},
 {id: 45, name: 'DB Skullcrusher', type: 'Isolation', targets: 'a'},
 {id: 46, name: 'Cable Pushdown - Bar', type: 'Isolation', targets: 'a'},
 {id: 47, name: 'Cable Pushdown - Rope', type: 'Isolation', targets: 'a'},
 {id: 48, name: 'Close Grip Bench', type: 'Compound', targets: 'acs'},
 {id: 49, name: 'Dips', type: 'Compound', targets: 'acs'}
];
